// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    Highlight: typeof import('./src/components/highlight/src/index.vue')['default']
    Src: typeof import('./src/components/highlight/src/index.vue')['default']
  }
}

export { }
